# Generated by Django 5.0.7 on 2024-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='market',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='signal',
        ),
        migrations.AddField(
            model_name='signal',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='strength',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
